### PR TITLE
initialize mamba too if it exists

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
cc @wolfv

**Comment by wolfv** [comment]
cool, this is great!

**Comment by ericpre** [comment]
Is it worth updating the [script](https://github.com/conda/constructor/blob/master/constructor/osx/update_path.sh) used by the osx installer?

**Comment by isuruf** [comment]
@ericpre, I haven't checked OSX pkg installers, so I'm not sure

**Comment by mcg1969** [comment]
I personally don't have a problem with handling Mac and/or Windows with separate PRs. @jezdez what do you think?

**Comment by hoechenberger** [comment]
I'd love to see this feature added :) If there's any way I could help add this, please let me know.

**Comment by jezdez** [comment]
@mcg1969 Yeah, same really, in absence of a better way to call non-conda init scripts this is a good work-around.

**Review by jezdez — APPROVED** [review]

**Comment by wolfv** [comment]
Looks like this is still green. Merging would be nice!

**Comment by stefanv** [comment]
This would really help simplify explaining the workflow to beginners!

**Comment by wolfv** [comment]
@isuruf @chrisburr as there are now two open PRs that seem necessary for a proper miniforge/mambaforge build I am wondering if we should fork `constructor` either to the `conda-forge` organization or the `mamba-org` organization where we can merge PRs easier?

**Comment by jezdez** [comment]
> @isuruf @chrisburr as there are now two open PRs that seem necessary for a proper miniforge/mambaforge build I am wondering if we should fork `constructor` either to the `conda-forge` organization or the `mamba-org` organization where we can merge PRs easier?

Hey Wolf, thanks for the patience with this, can you elaborate how that would make this easier in the long-run?

**Comment by jezdez** [comment]
@wolfv Quick question since you mentioned another PR, is the other one #487?

**Comment by wolfv** [comment]
yes, exactly #487 
I think Miniforge is currently running from a couple of personal forks and that's not really a nice solution.
cf. https://github.com/conda-forge/miniforge/blob/b01e48e643f0b0470ad405ffe34fe42e855bc84e/scripts/build.sh#L27

If it's impossible to get simple PRs merged here, we can have a fork that is the proper source for Miniforge, either in mamba-org or in the conda-forge org.

**Comment by wolfv** [comment]
Yep, I think these two PR's would be great for Miniforge. Then we don't need personal branches anymore.

**Comment by SylvainCorlay** [comment]
@jezdez I would be super interested in a release of constructor including that change.

**Comment by jezdez** [comment]
> @jezdez I would be super interested in a release of constructor including that change.
> 
> What are the plans for the next release?

Good question! The past few releases were done by @mcg1969 and I'd want to let him chime in on whether he has the time to do it. But failing that, the conda team at Anaconda could take a stab at it, it's [mostly just compat code](https://github.com/conda/constructor/compare/3.2.2...master), but it drops 2.7 finally. So probably would need to be a major version bump.

**Comment by mcg1969** [comment]
I'm not in a good position to crank on this, @jezdez, so it would be great if the team can take this one on.

**Comment by jezdez** [comment]
> I'm not in a good position to crank on this, @jezdez, so it would be great if the team can take this one on.

Cheers @mcg1969, no problem. @SylvainCorlay I'll take a stab at it some time this week, there is a lot going on so I'm not sure yet which day.

**Comment by stefanv** [comment]
@jezdez Did you happen to find some time to look at it?

**Comment by jezdez** [comment]
@stefanv Not yet, we've been super busy with the prep for the release of conda 4.12.0 and the libmamba solver.

**Pull request merged**
