### PR TITLE
Add tests for micromamba, transmutation and miniforge (continued)

### PR DESCRIPTION
**Pull request by jaimergp**
### Description

Continues and closes #503 

### Checklist - did you ...

- [x] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [X] Add / update necessary tests?
- [x] Add / update outdated documentation?

### CODE REVIEW

**Comment by jaimergp** [comment]
@chrisburr Is https://github.com/mamba-org/mamba/issues/1497 behind the errors with micromamba+miniforge+transmutation?

**Comment by jaimergp** [comment]
Two bugs surfacing if `micromamba` is used:

- `.conda` transmutation
- Shortcuts not being created on Windows (need to investigate on VM to know what's going on).

**Comment by chrisburr** [comment]
> @chrisburr Is [mamba-org/mamba#1497](https://github.com/mamba-org/mamba/issues/1497) behind the errors with micromamba+miniforge+transmutation?

I don't think so. The errors are different and I've been using transmutation+micromamba without any issues.

**Comment by jaimergp** [comment]
Got it, thanks! I'll need to investigate locally 👷

**Comment by jaimergp** [comment]
Ok, the "only" bug left now is Windows+micromamba+shortcuts. TBD.

**Comment by jaimergp** [comment]
More details about the errors:

```
Creating Miniforge3 menus...
The following argument was not expected: --make-menus
Run with --help for more information.
::error:: Failed to create menus
```

`micromamba` does not seem to support creating menus directly.

```
% micromamba.exe constructor [OPTIONS]

Options:
  -h,--help                   Print this help message and exit
  -p,--prefix TEXT            Extract the conda pkgs in <prefix>/pkgs
  --extract-conda-pkgs        Extract the conda pkgs in <prefix>/pkgs
  --extract-tarball           Extract given tarball into prefix
```

So we can't really test this for now. We could implement a fallback strategy via the bundled Python in `base` + `_nsis.py` integrations, but I don't want to add more coupling between the installer logic and the installer contents.

conda-forge is not using `micromamba` for Windows [as far as I can see](https://github.com/conda-forge/miniforge/blob/871e98647a95b99a769dd9f40669d06c44514bca/scripts/build.sh#L41-L55), so this is not critical. I'll add some documentation so people know what to expect.

**Comment by dbast** [comment]
Looks pretty good. Is the PR still in draft state or ready for review?

**Comment by jaimergp** [comment]
Yes I'll remove the draft status as soon as all is green. Hopefully this commit?

**Review by dbast — APPROVED** [review]

**Comment by jaimergp** [comment]
Last minute change :D Turns out `--make-menus` is always used on Windows, so all installers will fail there. We can change that in a future PR, but for now we'll error out if micromamba & windows are used together.

**Comment by chrisburr** [comment]
> Last minute change :D Turns out `--make-menus` is always used on Windows, so all installers will fail there. We can change that in a future PR, but for now we'll error out if micromamba & windows are used together.

It's probably better to fix this on the mamba side: https://github.com/mamba-org/mamba/issues/1215

**Comment by jaimergp** [comment]
Agreed!

**Review by dbast — APPROVED** [review]

**Pull request merged**
