### PR TITLE
Blacklist noarch python packages

### PR DESCRIPTION
**Pull request by ericdill**
Constructor is not yet compatible with noarch python packages as per the
discussion in https://github.com/conda/constructor/issues/86

This "fix" allows us to continue using constructor like we have been
previously before noarch: python packages started appearing. When the
fixes described in #86 land this fix can be reverted.

### CODE REVIEW

**Comment by jakirkham** [comment]
Would be great if someone could look at this. It is at least some improvement on the `noarch` situation with `constructor`.

**Comment by mingwandroid** [comment]
There's no point looking at this while it has conflicts.

AFAICT the end result of this approach is that old software that predates conda-forge's decision to prefer `noarch python` packages will get selected. Is that *really* a good outcome?

**Comment by jakirkham** [comment]
The result will be not producing broken installers quietly, which actually happens now and bit me recently.

**Comment by mingwandroid** [comment]
Broken because noarch python doesn't work? It will produce broken installers though and it will drop new packages for old ones, and it will do that silently. I honestly do not see the overall benefit of this.

**Comment by jakirkham** [comment]
No. Broken because `constructor` does not understand how `noarch: python` works. While `constructor` tries to include them, they cannot be imported, cannot be remove (by `conda`), and cannot be upgraded. It might be possible to force install them, but have no idea what kind of break one gets then.

**Comment by mingwandroid** [comment]
You have ignored the main thrust of my question twice now.

What use is an installer generator that (silently, or at all) creates installers based upon old software?

**Comment by mingwandroid** [comment]
I should also point out, since `noarch: python` will always require `conda` to be able to install it, this precludes `conda-forge` from marking *any* of `conda`'s dependencies as being `noarch: python`. I hope that fact new to you though!

**Comment by mingwandroid** [comment]
@ericdill, if you are still interested in this PR, then please address these issues:

1. It needs to be rebased.
2. It needs to warn in the strongest possible terms that it is dropping newer noarch packages for older non-noarch ones  (but not that it is dropping hundreds of packages that would never have made it into the installer finally anyway).

**Comment by ankostis** [comment]
Really stryugling with this `noarch` packages hidden in the stack...isn't it possible to had-fail (raise an exception) if a `noarch` package is met, until #86 is fixed?

**Comment by msarahan** [comment]
constructor supports noarch packages as of #263 - closing

**Pull request closed without merging**
