### PR TITLE
System info

### PR DESCRIPTION
**Pull request by martindurant**
Fixes https://github.com/conda/constructor/pull/134/files#r151166352

### CODE REVIEW

**Comment by goanpeca** [comment]
Hmmm if only we had a test ...

**Comment by martindurant** [comment]
@goanpeca , failed test says "pytest.vendored_packages.pluggy.PluginValidationError: Plugin 'pytest_cov' could not be loaded"

**Comment by martindurant** [comment]
cc @kalefranz

**Comment by nehaljwani** [comment]
@martindurant I re-triggered the build and it ran successfully. Could you please rebase the patch?

**Comment by martindurant** [comment]
@nehaljwani , should now be ready to package; but filling out PRs with more tests is certainly useful, if not as urgent.

**Comment by nehaljwani** [comment]
@martindurant 2.0.1 has been released 2.0.1. Let's target more code coverage and bug fixes for 2.0.2

**Comment by martindurant** [comment]
You mean this PR is included in 2.0.1?

**Comment by nehaljwani** [comment]
That's correct.

**Pull request merged**
