### PR TITLE
Fix aarch64 selector

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by jjhelmus** [comment]
LGTM, failing test is un-related.  Thanks for the fix @isuruf

**Comment by isuruf** [comment]
Thanks @jjhelmus. Is there going to be a release soon?

**Comment by jjhelmus** [comment]
> Thanks @jjhelmus. Is there going to be a release soon?

We typically make releases around the time that we release Miniconda/Anaconda installer.  There are releases of both planned in the next few weeks.  I'll check with the rest of the team on Monday but I think we can tag a release soon (in the next week).

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
