### PR TITLE
Introduce s390x support in constructor

### PR DESCRIPTION
**Pull request by pradghos**
- Introducing s390x support in constructor 
- This is the continuation of the work for s390x support -
conda - 
https://github.com/conda/conda/pull/9933
conda-build 
https://github.com/conda/conda-build/pull/3949

### CODE REVIEW

**Comment by pradghos** [comment]
@chenghlee @jjhelmus @mcg1969 : Please let me know if you have any review comments for this PR . Thank you very much !

**Comment by pradghos** [comment]
@jjhelmus @mingwandroid : Please let me know in case any of further review comments; Thank you !

**Comment by ravigumm** [comment]
Hi @jjhelmus and @mingwandroid, Would one of you please review and provide your comments ? Thanks.

**Comment by jjhelmus** [comment]
LGTM, merging.

**Comment by pradghos** [comment]
This is related to  https://github.com/conda/conda/issues/9791

**Pull request merged**
