### PR TITLE
Warn user if PYTHONPATH env var is set

### PR DESCRIPTION
**Pull request by nehaljwani**

### CODE REVIEW

**Comment by mingwandroid** [comment]
Thanks

**Comment by mingwandroid** [comment]
Hi @nehaljwani, I think we want a newline at the end of this, otherwise:

```
WARNING:
    You currently have a PYTHONPATH environment variable set. This may cause
    unexpected behavior when running the Python interpreter in Anaconda3.
    For best results, please verify that your PYTHONPATH only points to
    directories of packages that are compatible with the Python interpreter
    in Anaconda3: /root/anaconda3[root@cento632 ~]#
```

**Comment by mingwandroid** [comment]
(The `#` there is my prompt after installation).

**Comment by nehaljwani** [comment]
Ah, my zsh shell kept me in the dark about this. I pushed the fix.

**Pull request merged**
