### PR TITLE
Rdonnelly/allow noarch

### PR DESCRIPTION
**Pull request by mingwandroid**
Hi @ilanschnell, let me know if this is OK or if it needs more work. I think noarch is going to become increasingly important as we start to work on js and java packages.

### CODE REVIEW

**Comment by ilanschnell** [comment]
Ok, that should be fine.  However, it will only for the generic `noarch` packages.  Not for the so-called "Python noarch" ones.

**Comment by mingwandroid** [comment]
Thanks. I guess Python noarch ones have their own complications due to the (pointless) folder layout differences?

**Comment by ilanschnell** [comment]
Yes, Python noarch packages use a (generated) post link script to make the mapping of the site-packages work on all Platforms and for all Python versions.

**Comment by joelhullcio** [comment]
@ilanschnell @mingwandroid when will this change be released so I can use it?

**Comment by mingwandroid** [comment]
@joelhullcio, was this rolled out yet?

**Pull request merged**
