### PR TITLE
Ignore noarch python packages

### PR DESCRIPTION
**Pull request by ericpre**
Update PR #115.

I have used this branch to build installer for linux, windows and mac and it seems to do what it is supposed to do.

### CODE REVIEW

**Comment by ericpre** [comment]
It should be good now.

**Comment by nehaljwani** [comment]
@kalefranz What are your thoughts about this?

**Comment by tanishgupta1** [comment]
yes can we merge this pr soon. I am facing this issue for conda 4.2.9 where it tries to install noarch packages but conda 4.2 doesn't support no arch. Will this pr fix this scenerio ? I have filed it in anaconda group too 
https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/bzkOaFyVW0E

**Comment by ericpre** [comment]
@tanishgupta1: this repo is constructor, not conda.

**Comment by tleonhardt** [comment]
This PR may not be the right long-term solution, but it is a great quick fix for now.  It made the difference for me of ``constructor`` not working at all and it doing exactly what I want.

**Comment by tleonhardt** [comment]
Would it be possible to revisit this PR now that #217 has been merged into master?

**Comment by H0R5E** [comment]
I've taken a crack at this in #225.

**Comment by msarahan** [comment]
As of #263, constructor supports noarch packages. closing.

**Pull request closed without merging**
