### PR TITLE
Add tests for header template preprocessing and fix initialize by default

### PR DESCRIPTION
**Pull request by hmaarrfk**
It seems that nested if statements are not supported by the template processor.

The choice of template processor is rather secondary for me. This seems like the minimal fix things to pass.

I also added tests so that new features don't go silently "forgotten" so as to avoid this happening again.

### CODE REVIEW

**Review by ericpre — COMMENTED** [review]
I have closed #458 in favour of this PR - see https://github.com/conda/constructor/pull/458#issuecomment-920287212

It looks good from reading the code but I haven't tested the installer.

**Comment by hmaarrfk** [comment]
Kind ping

**Comment by mcg1969** [comment]
Working on this now

**Review by mcg1969 — COMMENTED** [review]
thanks!

**Pull request merged**
