### PR TITLE
Add no scripts option for windows installers

### PR DESCRIPTION
**Pull request by ericpre**
Add no scripts option to windows installers. The can be used when installing in silent mode:
```
Installer_name_exe /NoScripts=1 /S /D=installation_director
```
Or in through the gui by checking the "Do not run post install script.", which will be displayed if the `post_install_desc` key is provided in `construct.yaml`.

### CODE REVIEW

**Comment by ericpre** [comment]
I should have already signed the CLI.

**Comment by msarahan** [comment]
@cla-bot check

Sorry @ericpre it's a semi-manual process, and it's easy for us to get behind.  It should be good from now on for you.

**Comment by ericpre** [comment]
Thanks @msarahan, no worries!

**Comment by forrestwaters** [comment]
Thanks again @ericpre

**Pull request merged**
