### PR TITLE
Bye bye libconda!

### LINKED ISSUE #139: Consider removing libconda support from constructor
As @nehaljwani mentioned in #130, with libconda growing further and further out of date from conda, it might be appropriate to remove libconda support from constructor.  When constructor is using libconda, end-users will often end up with broken behavior that is subtle and not easy to trace back to libconda vs conda.

The drawback is that as of conda 4.3, conda can only be installed in the root conda environment.  This restriction is lifted in conda 4.4.

### PR DESCRIPTION
**Pull request by nehaljwani**
Fixes #139

### CODE REVIEW

**Comment by kalefranz** [comment]
If we merge this, we should probably bump the major version of constructor to 3.0, no?

**Comment by nehaljwani** [comment]
libconda was already unusable with the 2.0.0 release, which was a major bump. This commit just removed the unnecessary burden. Should we still make the next release 3.0.0 ? Thoughts, @mingwandroid ?

**Comment by kalefranz** [comment]
> libconda was already unusable with the 2.0.0 release, which was a major bump

In that case I'm fine keeping major version at 2.

**Comment by mingwandroid** [comment]
2.x is ok with me. 3 should be a rewrite to use a proper installation system and a static installer executable ;-)

**Comment by kalefranz** [comment]
And `libconda` should actually be... you know... a dynamic library you can link compiled code against.

**Comment by mingwandroid** [comment]
it could be built as both static and shared, incase you wanted to make a static executable out of it.

**Comment by kalefranz** [comment]
Yes, exactly.

**Pull request merged**
