### PR TITLE
Force use of nsis 3.01 on Windows

### PR DESCRIPTION
**Pull request by jaimergp**
Temporary workaround for the CI issues we are seeing as part of #526

### CODE REVIEW

**Comment by scottwsides** [comment]
Hi Jaime, I'm only asking this here because of your recent merge of the branding branch. A minor problem first... for a while I've been seeing

```
No local packages or working download links found for ruamel_yaml
error: Could not find suitable distribution for Requirement.parse('ruamel_yaml')
```

which normally just keeps going, but now no pkg file gets made, so I didnt know if this was something new. Also, since branding I see

```
Checking mac signature
pkgutil: option `--check-signature' requires an argument``
```

which was working in your branch. I'm building just by cloning source, going into my conda environment and doing

`python setup.py install`

Is this not the standard way?  Thanks!

**Comment by jaimergp** [comment]
To get the dev version I'd do something like this:

```
$ conda create -n constructor-dev constructor pip
$ conda activate constructor-dev
$ conda remove --force constructor
$ pip install https://github.com/conda/constructor/archive/main.tar.gz --no-deps
```

Try that and let me know if it works!

**Comment by scottwsides** [comment]
Thanks, I will try that. But I want to understand why building main doesnt work. Didnt you merge changes from osx-branding into main? I just want to be prepared for changes later (when I forget what has happened) and my installers might break.

**Comment by jaimergp** [comment]
We don't use that option of `pkgutil` directly so no clue what might be wrong. If the issue persists please open an issue with more details about your installation and input files.

**Comment by scottwsides** [comment]
Sorry.... the pkgutil error is a red-herring. Thats in my script and is dying simply because constructor is failing. The pip install is fine... but I'm getting

phoenix:hpccloud-trunk swsides$ cs-env/bin/constructor --verbose chemistream-constructor
platform: osx-64
conda packages download: /Users/swsides/.conda/constructor/osx-64
Traceback (most recent call last):
  File "cs-env/bin/constructor", line 8, in <module>
    sys.exit(main())
  File "/Users/swsides/hpccloud-trunk/cs-env/lib/python3.8/site-packages/constructor/main.py", line 244, in main
    main_build(dir_path, output_dir=out_dir, platform=args.platform,
  File "/Users/swsides/hpccloud-trunk/cs-env/lib/python3.8/site-packages/constructor/main.py", line 112, in main_build
    fcp_main(info, verbose=verbose, dry_run=dry_run, conda_exe=conda_exe)
  File "/Users/swsides/hpccloud-trunk/cs-env/lib/python3.8/site-packages/constructor/fcp.py", line 398, in main
    _urls, dists, approx_tarballs_size, approx_pkgs_size, has_conda = _main(
  File "/Users/swsides/hpccloud-trunk/cs-env/lib/python3.8/site-packages/constructor/fcp.py", line 251, in _main
    print("specs: %r" % specs)
TypeError: not all arguments converted during string formatting

Again... nothing else about my construct.yaml has changed that works with your osx-branding.

**Comment by jaimergp** [comment]
That looks like your `construct.yaml` has some kind of issue in the `specs` field. Can you post the contents of that file here?

**Comment by scottwsides** [comment]
So I switched back to your branch... and I'm still getting same errors. The first error is the ruamel_yaml 'Parse distribution' error. I dont think anything else in my build script has changed. So I cant build at all on mac now... which is kinda serious.

**Comment by jaimergp** [comment]
Can you DM me on gitter? http://gitter.im/jaimergp

**Comment by scottwsides** [comment]
Sure... I'm on gitter now, I think. I havent used gitter before.

**Pull request merged**
