### PR TITLE
FIX: preserving proxy_servers and ssl_verify settings

### PR DESCRIPTION
**Pull request by gabrielcnr**
Fix for Issue #304 - in my case I'm running constructor from a corporate environment behind proxies and interfacing with conda channels behind artifacts repositories which require ssl verification to access.
With this patch in place I was able to successfully build my installer with constructor.

### CODE REVIEW

**Review by marcelotrevisani — APPROVED** [review]

**Comment by marcelotrevisani** [comment]
Hi @mcg1969 ,
Could you please review/merge this PR?
Just a friendly ping :)

**Comment by mcg1969** [comment]
Sorry y'all, I get so many conda notifications its hard to separate the wheat from the chaff. Thanks for the ping. On it

**Comment by gabrielcnr** [comment]
Hey @mcg1969 Thanks for merging this.

Would you be able to kindly confirm when can we expect to see this change released in build release version `3.1.1` ? Thanks

**Comment by mcg1969** [comment]
@gabrielcnr I'm afraid I don't have a solid answer right now. However, note that each master commit is built into a conda package, and available in the `dev` subchannel. So for instance,
```
conda install ctools/label/dev::constructor
```
should get you the latest build including all of the recent merged PRs.

**Pull request merged**
