### PR TITLE
Release 3.2.1

### LINKED ISSUE #418: Update CHANGELOG for v3.2.0
@mcg1969 @isuruf @hmaarrfk @gabrielcnr 
The changelog needs updating, so I've atted all the folks who contributed since 3.1.0. I pasted the template here and figure we can use this issue to edit it together. I've included the fixes/features I was responsible for already. If you can't edit this issue, just copy/paste the template to the next comment to add your updates.

**Edit 1/4/2021:** I went through the comments and added them into this template so it is now up-to-date. Any NSIS  or PKG items?

2020-11-14   3.2.0:
-------------------
  * COMMON:
    - `construct.yaml` file now reads environment variables during the Jinja2 parsing stage. Env vars can be included like: `{{ environ["ENV_VAR"] }}` (#413).
    - Fixed bug where constructor crashed if a listed spec was in a noarch-only channel (i.e. without a subdir for the specific platform) (#409).
    - Avoid adding newly installed environment to the list of global conda environments if conda isn't included in the installer itself. (#372)

  * SHELL:
    - The user-shell initialisation phase of the installer is no longer included in the install script if there is no conda available in the installed environment.
    - The "test" option is only available if conda is installed in the environment. Previously this would fail in this situation.

  * NSIS:
    - ?

  * PKG:
    - ?

### PR DESCRIPTION
**Pull request by FaustinCarter**
Updated authors list and changelog. This is ready to be merged and tagged as 3.2.1

Closes #418

### CODE REVIEW

**Comment by FaustinCarter** [comment]
@mcg1969 This is ready for review. I'm not clear on exactly what the release process is here, so I've held off on tagging anything.

**Comment by FaustinCarter** [comment]
Also, just a note: I tried running the `scripts/make_docs.py` script to regenerate `CONSTRUCT.md`, but for some reason that actually removed several entries that should be there, so I left it as is after verifying it seemed to be correct.

I also was not sure about whether or not the `rever` tool is still in use, but if that's how you do releases, I recommend _skipping_ the authors step, since I already did that, and it will almost certainly crash on you due to one of the authors (ahem @nerohmot) having a non-UTF8 character in his name that rever chokes on (I fixed it up manually after the fact, but someone should patch rever).

**Comment by mcg1969** [comment]
I don't know how to use `rever` I am afraid. Honestly I am fine removing it, since those of us who are maintaining this the most need to know the tools.

But if CONSTRUCT.md is not being built correctly, it is a problem we need to solve. The master reference for the documention is in `construct.py`:

https://github.com/conda/constructor/blob/master/constructor/construct.py

Can you let me know which ones were removed?

**Comment by FaustinCarter** [comment]
> I don't know how to use `rever` I am afraid. Honestly I am fine removing it, since those of us who are maintaining this the most need to know the tools.
> 
> But if CONSTRUCT.md is not being built correctly, it is a problem we need to solve. The master reference for the documention is in `construct.py`:
> 
> https://github.com/conda/constructor/blob/master/constructor/construct.py
> 
> Can you let me know which ones were removed?

OK, I think this was a false alarm. I ran it again just now and it produced exactly the same file. Maybe I accidentally diffed it against the wrong commit when I was checking earlier. I think we are good to go.

**Pull request merged**
