### PR TITLE
fix cache directory creation

### LINKED ISSUE #411: macOS download_dir does not exist or is not writable, unless in verbose mode
Hi all,

I have constructor 3.1.0 from `conda install -y ctools/label/dev::constructor`
and when I try to create a new installer from the environment, I get the following error:
```
❯❯❯ constructor --cache-dir cache --output-dir dist .                                                                                                                           
platform: osx-64
Traceback (most recent call last):
  File "/Users/user/miniconda3/envs/test/bin/constructor", line 11, in <module>
    sys.exit(main())
  File "/Users/user/miniconda3/envs/test/lib/python3.8/site-packages/constructor/main.py", line 243, in main
    main_build(dir_path, output_dir=out_dir, platform=args.platform,
  File "/Users/user/miniconda3/envs/test/lib/python3.8/site-packages/constructor/main.py", line 111, in main_build
    fcp_main(info, verbose=verbose, dry_run=dry_run, conda_exe=conda_exe)
  File "/Users/user/miniconda3/envs/test/lib/python3.8/site-packages/constructor/fcp.py", line 383, in main
    _urls, dists, approx_tarballs_size, approx_pkgs_size, has_conda = _main(
  File "/Users/user/miniconda3/envs/test/lib/python3.8/site-packages/constructor/fcp.py", line 309, in _main
    pc_recs = _fetch(download_dir, precs)
  File "/Users/user/miniconda3/envs/test/lib/python3.8/site-packages/constructor/fcp.py", line 110, in _fetch
    assert pc.is_writable, download_dir + " does not exist or is not writable"
AssertionError: [---redacted---]/cache/osx-64 does not exist or is not writable
```

However, if I run it with the `-v` option, it does run successfully 😮 

I noticed that the setuid bit is set when using `-v`, but not otherwise.

```
❯❯❯ constructor -v --cache-dir cache --output-dir dist .
[...]

❯❯❯ ls -lha | grep cache
drwxrwsr-x   3 user  1244544504    96B Oct 31 21:24 cache

❯❯❯ rm -rf cache                                                                                                                                                             

❯❯❯ constructor --cache-dir cache --output-dir dist .
[...Error above...]

❯❯❯ ls -lha | grep cache
drwxr-x---   3 user  1244544504    96B Oct 31 21:24 cache

```

Any clues?

How to reproduce:
Install miniconda
```
./Miniconda3-latest-MacOSX-x86_64.sh

Welcome to Miniconda3 py38_4.8.3
...
```
 
open a new session:
```
❯❯❯  conda -V
conda 4.8.3

❯❯❯ conda create -y -n myenv python=3.8.5
❯❯❯ conda activate myenv
❯❯❯ conda install -y ctools/label/dev::constructor
❯❯❯ cat construct.yaml                                                                                                                                                      
name: test_installer
version: 1.0.0

channels:
  - http://repo.anaconda.com/pkgs/main/
  - https://repo.anaconda.com/pkgs/main/osx-64  [osx]
  - https://repo.anaconda.com/pkgs/main/noarch

environment: myenv
```

Thanks in advance.

### PR DESCRIPTION
**Pull request by jaimergp**
### Description

Closes #411 

### Checklist - did you ...

- [x] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

### CODE REVIEW

**Comment by larsoner** [comment]
@jaimergp is this one ready?

**Comment by jaimergp** [comment]
I cannot reproduce the original issue, so no clue. Hoping @hoechenberger can take a look :D

**Comment by hoechenberger** [comment]
Sorry, I cannot test this at the moment :( but the changes look good to me

**Comment by jaimergp** [comment]
@phyordia Can you take a look here? It would help a lot if you could confirm whether this fixes the bug you found! Thanks!

**Comment by phyordia** [comment]
@jaimergp Thanks for the PR, but I don't think it fixes the bug, only makes it more interesting: now it sets set setuid bit correctly, but the "not writable" code is still there.

same setup as described in #411 , but using the latest miniconda and on a M1 machine now instead.

```
(base) [redacted] % constructor   --cache-dir cache --output-dir dist .
platform: osx-arm64
MKDIR SAFE!!!  <-- @phyordia added this to the PR code just to make sure it was going through the changes. 
Traceback (most recent call last):
  File "[redacted]/miniconda3/bin/constructor", line 8, in <module>
    sys.exit(main())
  File "[redacted]/miniconda3/lib/python3.9/site-packages/constructor/main.py", line 272, in main
    main_build(dir_path, output_dir=out_dir, platform=args.platform,
  File "[redacted]/miniconda3/lib/python3.9/site-packages/constructor/main.py", line 136, in main_build
    fcp_main(info, verbose=verbose, dry_run=dry_run, conda_exe=conda_exe)
  File "/[redacted]/miniconda3/lib/python3.9/site-packages/constructor/fcp.py", line 460, in main
    has_conda, extra_envs_info) = _main(
  File "[redacted]/miniconda3/lib/python3.9/site-packages/constructor/fcp.py", line 401, in _main
    pc_recs, _urls, dists, has_conda = _fetch_precs(
  File "[redacted]/miniconda3/lib/python3.9/site-packages/constructor/fcp.py", line 334, in _fetch_precs
    pc_recs = _fetch(download_dir, precs)
  File "[redacted]/miniconda3/lib/python3.9/site-packages/constructor/fcp.py", line 113, in _fetch
    assert pc.is_writable, download_dir + " does not exist or is not writable"
AssertionError: [redacted]/constructor_test/cache/osx-arm64 does not exist or is not writable
```

sets the last "x" correctly:
```
(base) [redacted] % ls -lha | grep cache
drwxrwsr-x   3 [redacted]    96B Aug 16 09:19 cache 
(base) [redacted] % ls -lha cache
drwxrwsr-x  2 [redacted]   64B Aug 16 09:19 osx-arm64
```


If I pull out the `_find_out_of_date_precs()` outside of the `if verbose:` in  `fcp.py` line 320, it works just fine!:

```
    precs = exclude_packages(precs, exclude, error_on_absence=not extra_env)
    more_recent_versions = _find_out_of_date_precs(precs, channel_urls, platform)
    if verbose:
        _show(name, version, platform, download_dir, precs, more_recent_versions)
```

I didn't have much time yet to explore this rabbit hole, but definitely something downstream from `_find_out_of_date_precs()` makes it work.

**Comment by jaimergp** [comment]
Thanks @phyordia! Well, I think it's still due to that `SubdirData.query_all` function, which relies on `create_cache_dir`. The other call in that function is to `PackageCacheData.first_writable()`, which _also_ has directory-creating side effects :D 

Funnily enough, the classmethod ends up calling the sudo-safe mkdir thingy, so we'll see if we had missed something. Pushing a new commit in a minute. Could you try please?

**Comment by phyordia** [comment]
@jaimergp  actually the fix is quite simple(r). I'll submit a PR soon.

**Review by hoechenberger — APPROVED** [review]
Code looks good, feel free to merge if you believe it actually fixes the issue :)

**Pull request merged**
