### PR TITLE
Fix for the Redirect link for the edit source

### PR DESCRIPTION
**Pull request by RahulARanger**
### Checklist - did you ...

- [X] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [X] Add/update necessary tests?
- [X] Add/update outdated documentation?

### Description

Hi, The Pull request for the following things:

1. To fix the Edit Source Link in the existing documentation, Previously we were referring to the `https://github.com/conda/constructor/edit/main/docs/...` expected: `https://github.com/conda/constructor/edit/main/docs/source/...`
2. emphasized `.exe` along with packages for macOS and Linux in the page: Getting Started 
image
3. Removed a Preposition "of" in Getting Started Page

### CODE REVIEW

**Comment by jaimergp** [comment]
Thanks!

Can you also add a `news` file? Once you've signed the CLA, we can merge.

**Comment by RahulARanger** [comment]
> Thanks!
> 
> Can you also add a `news` file? Once you've signed the CLA, we can merge.

Done, is it possible to ping CLA Check again?

**Comment by jaimergp** [comment]
> Done, is it possible to ping CLA Check again?

@dbast can you check please? 🙏

**Comment by jaimergp** [comment]
Oh, it's checked. Cool. Then we can merge once CI is passing :D

**Comment by jaimergp** [comment]
Thanks!

**Pull request merged**
