### PR TITLE
add note on Windows channels /free and /msys2

### PR DESCRIPTION
**Pull request by electronwill**
add note on Windows channels /free and /msys2, based on discussion today in Flowdock channel "Anaconda Distribution" with @trentoliphant and @mingwandroid .

### CODE REVIEW

**Comment by electronwill** [comment]
Good point. Would this be better?

"It is best to add `/msys2` as `http://repo.continuum.io/pkgs/msys2`. Be sure no firewall is set to block this URL."

**Comment by mingwandroid** [comment]
Well I don't think we mention firewalls for repo.continuum.io in general, so we shouldn't here either.. that anaconda.org also has the packages is just because the are rsynced from there to repo.

Though it is am alternative route to the same packages ...

**Comment by electronwill** [comment]
Thank you-- that makes sense!

**Comment by ilanschnell** [comment]
I've manually made the changes to master, because there was a conflict.  Thanks @electronwill

**Pull request closed without merging**
