### PR TITLE
Get channels urls using conda

### PR DESCRIPTION
**Pull request by ericpre**
Revisit #231 to allow using channels name in `construct.yaml`, for example:

```
channels:
  - defaults
  - conda-forge
```

### CODE REVIEW

**Comment by ericpre** [comment]
Is there a plan for considering this PR? If so, having an idea of when it would be reviewed would be useful.
I will solve the conflict when someone get time to review it and give feedback on the approach, to avoid spending time on it for nothing.

Same for #292 and ##288.

**Comment by msarahan** [comment]
sorry, constructor typically gets neglected in between Anaconda releases.  We will begin working on the next Anaconda release early in January, so I think you can expect to see more attention then if we don't get to it sooner.

**Comment by ericpre** [comment]
OK, thanks for the update on the timing.

**Comment by forrestwaters** [comment]
@ericpre thanks for the contributions and apologies for the poor response times. Looks like this one breaks the [channels_remap functionality](https://github.com/ericpre/constructor/blob/channels_urls/CONSTRUCT.md#channels_remap) which we unfortunately don't have tests for. 
I think we need to remove these trailing slashes: https://github.com/conda/constructor/blob/0d4df820864465cfc2de2e73c75b01d39e5d4d63/constructor/preconda.py#L47
The other CI test failure is unrelated and is something we will need to fix. We will be starting on the next release in the next few weeks and will be sure this and your other PRs get reviewed properly. Thanks again!

**Comment by ericpre** [comment]
Yes, indeed, some trailing slashes needed to be removed. When solving the merge conflict, I checked it for [remapping from a folder to an url](https://github.com/conda/constructor/pull/306/files#diff-10afcf5d28ad04ccb09235831e8ccc11R61,) but it was still breaking remapping from one url to another.

I have tried with:
```
name: MinicondaX
version: X

install_in_dependency_order: True

channels:
  - defaults

channels_remap:
  - src: file:///opt/miniconda3/conda-bld
    dest: https://repo.anaconda.com/pkgs/main

  - src: https://repo.anaconda.com/pkgs/main/
    dest: https://repo.anaconda.com/pkgs/main/

specs:
  - python 3.7*
  - conda
```
and it seems to work.

**Comment by forrestwaters** [comment]
Thanks!

**Pull request merged**
