### PR TITLE
Create CODEOWNERS

### PR DESCRIPTION
**Pull request by jezdez**
### Description

Similar to https://github.com/conda/menuinst/pull/104

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

### CODE REVIEW

**Review by isuruf — APPROVED** [review]

**Comment by isuruf** [comment]
@jezdez, currently I can only approve as part of @conda/constructor team, but cannot merge PRs. Was that intentional? We approve a PR, but ping a @conda/core person to merge?

**Comment by jezdez** [comment]
@isuruf That was because this PR still applied the previous CODEOWNERS file (having conda/conda-core listed) to this PR. I've enabled enforcing the CODEOWNERS branch protection feature, now that we have an official team for those projects.

**Comment by jezdez** [comment]
In other words, this should now work in the other open PRs.

**Comment by isuruf** [comment]
Thanks. Can you try approving #540 to check?

**Comment by jezdez** [comment]
@isuruf Sure, but that didn't actually apply the CODEOWNERS review requirement since it didn't change anything :)

**Comment by isuruf** [comment]
I still see

image

**Comment by jezdez** [comment]
@isuruf Huh, seems like write permission might not be enough? Just elevated the constructor team to "maintain" permission. Does that work now?

**Comment by isuruf** [comment]
Yes, I can merge now. Thanks.

**Comment by jezdez** [comment]
@isuruf Sorry for the oversight!

**Comment by isuruf** [comment]
No worries. Thanks for facilitating the new @conda/constructor team.

**Pull request merged**
