### PR TITLE
catch install-time errors on windows

### LINKED ISSUE #544: Latest multi-dev breaks windows
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

The following works for windows installer build. If the git checkout line is removed.... it definitely breaks. 

```
git clone https://github.com/conda/constructor.git cs-constructor

echo -----------
cd  cs-constructor
git checkout 8426b02ca72d277fa7f538577445e8f5da0bd573 .  <-----------------------------
rem python setup.py install
python -m pip install -e . --no-deps

```
### Conda Info

_No response_

### Conda Config

_No response_

### Conda list

_No response_

### Additional Context

_No response_

### LINKED ISSUE #551: [CI] Windows tests can pass with errors
The `/S` (silent) mode of NSIS does not really error out if something goes wrong. So we won't catch errors at install time, only at build time. It doesn't really produce any logs directly either, but [there are NSIS builds that can](https://nsis.sourceforge.io/Special_Builds).

I'll look into using these in our CI...

### PR DESCRIPTION
**Pull request by jaimergp**
### Description

Closes #544 

Closes #551 

In #509 I forgot to add one piece of the conda packages extraction logic. This resulted in failed installs. Readding this piece fixes #544.

However, this error wasn't caught by the CI pipeline because of #551!

Note that the silent mode of NSIS installers (`/S`) does _not_ print anything to STDOUT. Additionally, most of the dialogs are configured to "ignore" the warning if an error occurred, thus moving on. The exit code does not change with errors! We can't rely on that to detect whether something failed. Instead, the solution was:

* The CI now uses a special NSIS build with log-dumping abilities (normal NSIS does not have this feature). I want to add [`*log*` variants](https://github.com/conda-forge/nsis-feedstock/pull/21) to the `nsis` package in conda-forge/defaults, but for now we are manually patching.
* Errors are printed to the log file, even if ignored
* `conda install ...` step will throw an error too, if needed (it didn't before!)
* The CI will inspect the log for `:error:` strings planted by our NSI script
* If there were any errors, these are printed and reported the installer is reported as failing.

### Checklist - did you ...

- [x] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [X] Add / update necessary tests?
- [ ] Add / update outdated documentation?

### CODE REVIEW

**Comment by jaimergp** [comment]
Finally, we have eyes on Windows :D 

This is ready for review now.

**Comment by jaimergp** [comment]
Note Windows are now failing, as reported in #544 - we want to merge with failures. I'll debug 544 in a separate PR.

**Review by larsoner — APPROVED** [review]
LGTM +1 for merge

**Review by hoechenberger — APPROVED** [review]

**Comment by hoechenberger** [comment]
Thanks @jaimergp!

**Pull request merged**
