### PR TITLE
Update header.sh

### PR DESCRIPTION
**Pull request by nerohmot**
[conda/constructor#348](https://github.com/conda/constructor/issues/348)
[conda-forge/miniforge#40](https://github.com/conda-forge/miniforge/issues/40)

### CODE REVIEW

**Comment by jjhelmus** [comment]
@cla-bot check

**Comment by nerohmot** [comment]
@marcelotrevisani, could you please review and merge the change ?

**Comment by marcelotrevisani** [comment]
> @marcelotrevisani, could you please review and merge the change ?

I don't' have permissions to merge code on ``conda/constructor``
@jjhelmus should be able to review/merge it :)

**Comment by jjhelmus** [comment]
LGTM

**Comment by nerohmot** [comment]
@jjhelmus : thanx! 
How does it work for a new release ? (a lot of changes where merged since the 3.0.1 release)
Would like to build a new conda-forge/miniforge against the new conda/constructor :pray:

**Pull request merged**
