### PR TITLE
force prefix if passed as kwarg so standalone doesnt fallback to.…

### PR DESCRIPTION
**Pull request by forrestwaters**
…sys.prefix

### CODE REVIEW

**Comment by msarahan** [comment]
We may want to think about a way for people to update their standalone. As it is, this will not fix old installations, only new ones created by installers that have this fix (which obviously won't be available until the next Anaconda and miniconda releases).

**Comment by mcg1969** [comment]
Note: `normpath` does not reliably remove all duplicate slashes. Sophia's `normalize_path` does, but it doesn't work on Windows. However, that can be fixed; see, for example, #315

**Comment by jjhelmus** [comment]
I think  6afc3d771f5160b9caaa07b3f9ca9b5b49a61714 and 6ffc7c2f1464c9ba5a3ec29015a9d893f5c91e33 can be dropped given the changes to `normalize_path` in #315

**Comment by forrestwaters** [comment]
Thanks, I removed those changes and rebased

**Comment by jjhelmus** [comment]
Thanks @forrestwaters

**Pull request merged**
