### PR TITLE
[MRG] add support for conda-build's local channel

### PR DESCRIPTION
**Pull request by croth1**
@ilanschnell, this hack should allow to get access to conda-build's local channel. Are you in principle interested in allowing this?

### CODE REVIEW

**Comment by croth1** [comment]
I changed the PR and now replace all channels named `local` with the path to the local channel. This fixes a bug when the channel description lists `local` multiple times.
I also added an informative error message when trying to use `local` channels although conda-build is not installed.

Should be ready for a first round of reviews.

**Comment by croth1** [comment]
Any progress on this? Are there plans to implement this?

**Comment by ericdill** [comment]
@croth1 I suppose this was closed because of the radio silence from the continuum folks?  Did you ever get any contact about this feature?

**Comment by croth1** [comment]
@ericdill, I still would be very interested in getting this feature, but I never got any feedback from continuum folks.

**Comment by mingwandroid** [comment]
Can you comment on this please @ilanschnell?

**Comment by ericdill** [comment]
@croth1 so it looks like you can actually include locally built conda packages.  I spent a few hours last night poking and prodding conda and constructor.  Here's what you need to do to include arbitrary locally built conda packages

### Include default conda build path

You can include the default `conda-bld` path as a channel. Let's say you have conda installed at /home/user/miniconda.  You can include the conda-bld directory as such:

```
- file:///home/user/miniconda/conda-bld
```
as a channel in your construct.yaml and `constructor` will pick up that channel.

### Include an arbitrary folder location

To include an arbitrary local folder (as a channel) in a constructor, you can do the following:

Let's assume we are on the linux-64 platform and have a conda package in the directory /tmp/foo. it needs to be moved to 

```
/tmp/foo/linux-64
```

then you need to index it with
```
conda index /tmp/foo/linux-64
```

then and very importantly you need to make a `noarch` dir. `constructor` implicitly adds the `noarch` directory to the search path [as seen here](https://github.com/conda/constructor/blob/2aa1d8aff7d69e217886c8a403c3253c64028003/constructor/fcp.py#L177-L180) which will result in the stack trace at the end if you don't make the `noarch` dir

```
mkdir /tmp/foo/noarch
```

and then index it

```
conda index /tmp/foo/noarch
```
and finally you can include 
```
- file:///tmp/foo
```
as one of the channels

#### Missing noarch stack trace

```
.........Traceback (most recent call last):
  File "/home/edill/miniconda/bin/constructor", line 6, in <module>
    sys.exit(main())
  File "/home/edill/miniconda/lib/python3.5/site-packages/constructor/main.py", line 149, in main
    verbose=opts.verbose)
  File "/home/edill/miniconda/lib/python3.5/site-packages/constructor/main.py", line 84, in main_build
    fcp.main(info, verbose=verbose)
  File "/home/edill/miniconda/lib/python3.5/site-packages/constructor/fcp.py", line 179, in main
    for url in info['channels']
  File "/home/edill/miniconda/lib/python3.5/site-packages/libconda/utils.py", line 68, in __call__
    value = self.func(*args, **kw)
  File "/home/edill/miniconda/lib/python3.5/site-packages/libconda/fetch.py", line 219, in fetch_index
    repodatas.append((url, future.result()))
  File "/home/edill/miniconda/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/home/edill/miniconda/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/home/edill/miniconda/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/edill/miniconda/lib/python3.5/site-packages/libconda/fetch.py", line 62, in func
    res = f(*args, **kwargs)
  File "/home/edill/miniconda/lib/python3.5/site-packages/libconda/fetch.py", line 98, in fetch_repodata
    headers=headers, proxies=session.proxies)
  File "/home/edill/miniconda/lib/python3.5/site-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/home/edill/miniconda/lib/python3.5/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/edill/miniconda/lib/python3.5/site-packages/requests/sessions.py", line 641, in send
    r.content
  File "/home/edill/miniconda/lib/python3.5/site-packages/requests/models.py", line 781, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/home/edill/miniconda/lib/python3.5/site-packages/requests/models.py", line 714, in generate
    chunk = self.raw.read(chunk_size)
AttributeError: 'FileNotFoundError' object has no attribute 'read'
```

**Comment by ericdill** [comment]
@mingwandroid @ilanschnell I can't tell if this is documented anywhere.  Would you be amenable to me submitting a docs PR to detail **how** to include locally built packages?

**Pull request closed without merging**
