### PR TITLE
Fix `channels_remap` and add regression test for percent-encoded packages

### PR DESCRIPTION
**Pull request by jaimergp**
### Description

Closes https://github.com/conda/constructor/issues/908

### Checklist - did you ...

- [x] Add a file to the `news` directory ([using the template](https://github.com/conda/constructor/blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [X] Add / update necessary tests?
- [ ] Add / update outdated documentation?

### CODE REVIEW

**Comment by jaimergp** [comment]
Trying to debug the `use_channel_remap` failures, I see they are not tied to the new `conda-libmamba-solver` release.

* I can reproduce locally with both conda-libmamba-solver 24.9 and 24.11
* The problem shows up for both conda-standalone 24.5 and 24.9
* It does NOT show up for micromamba
* The `PathNotFound` errors come from this command run as part of the installer (so the installer does get built):
```
+ CONDA_ROOT_PREFIX=/private/var/folders/1b/z374sygs1s96t_xxxv0hr3lr0000gn/T/pytest-of-jrodriguez/pytest-632/test_example_use_channel_remap0/install-use_channel_remap-0.0.1-MacOSX-arm64-sh
+ CONDA_REGISTER_ENVS=true
+ CONDA_SAFETY_CHECKS=disabled
+ CONDA_EXTRA_SAFETY_CHECKS=no
+ CONDA_CHANNELS=
+ CONDA_PKGS_DIRS=/private/var/folders/1b/z374sygs1s96t_xxxv0hr3lr0000gn/T/pytest-of-jrodriguez/pytest-632/test_example_use_channel_remap0/install-use_channel_remap-0.0.1-MacOSX-arm64-sh/pkgs
+ CONDA_QUIET=1
+ /private/var/folders/1b/z374sygs1s96t_xxxv0hr3lr0000gn/T/pytest-of-jrodriguez/pytest-632/test_example_use_channel_remap0/install-use_channel_remap-0.0.1-MacOSX-arm64-sh/_conda install --offline --file /private/var/folders/1b/z374sygs1s96t_xxxv0hr3lr0000gn/T/pytest-of-jrodriguez/pytest-632/test_example_use_channel_remap0/install-use_channel_remap-0.0.1-MacOSX-arm64-sh/pkgs/env.txt -yp /private/var/folders/1b/z374sygs1s96t_xxxv0hr3lr0000gn/T/pytest-of-jrodriguez/pytest-632/test_example_use_channel_remap0/install-use_channel_remap-0.0.1-MacOSX-arm64-sh --no-rc
```
  * That empty `CONDA_CHANNELS` is weird. Might come from the Jinja PR. Let me look into it because maybe it should not be empty? 🤔 
* Changing [these lines](https://github.com/conda/constructor/blob/b0a37b568ac7c939c8a43a7c20b4841ef34cf068/examples/use_channel_remap/construct.yaml#L9-L14) to their `https` counterparts, results in a different error. The installation does get through but the assertions in the test do not pass `AssertionError: assert 'pkgs/main' == 'private_repo'`.

**Comment by jaimergp** [comment]
> * That empty `CONDA_CHANNELS` is weird. Might come from the Jinja PR. Let me look into it because maybe it should not be empty? 🤔

Nah, `constructor 3.10` also does that:

```
CONDA_ROOT_PREFIX="$PREFIX" \
CONDA_REGISTER_ENVS="true" \
CONDA_SAFETY_CHECKS=disabled \
CONDA_EXTRA_SAFETY_CHECKS=no \
CONDA_CHANNELS="" \
CONDA_PKGS_DIRS="$PREFIX/pkgs" \
CONDA_QUIET="$BATCH" \
"$CONDA_EXEC" install --offline --file "$PREFIX/pkgs/env.txt" -yp "$PREFIX" $shortcuts --no-rc || exit 1
rm -f "$PREFIX/pkgs/env.txt"
```

And it also reproduces the error, btw.

**Comment by jaimergp** [comment]
Hm, in CI downgrading to CLS 24.9 does fix it! 🤔

**Review by marcoesters — COMMENTED** [review]
Should we update dependencies to not use libmamba 24.11.0?

**Comment by jaimergp** [comment]
Good idea. Probably worth a repodata patch too, althought it might be easier to mark as broken?

**Comment by marcoesters** [comment]
> Good idea. Probably worth a repodata patch too, althought it might be easier to mark as broken?

Patching is easier than marking it as broken because workflows may point to pinned versions of `constructor`. Marking it as broken can break these workflows.

**Comment by jaimergp** [comment]
Ugh, true.

**Pull request merged**
